agent/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView
app_name = 'agent'
urlpatterns =[

    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path("<int:pk>/", AgentDetailView.as_view(), name='agent-detail'),
    path("<int:pk>/update/", AgentUpdateView.as_view(), name='agent-update'),
    path("<int:pk>/delete/", AgentDeleteView.as_view(), name='agent-delete')
]

inventory/urls.py
from django.urls import path
from .views import (
    InventoryListView,
    TrackerDeviceListView,
    TrackerDeviceCreateView,
    TrackerDeviceDetailView,
    TrackerDeviceUpdateView,
    TrackerDeviceDeleteView,
    SimListView,
    SimCreateView,
    SimDetailView,
    SimUpdateView,
    SimDeleteView,
)

app_name = 'inventory'

urlpatterns = [
    path('', InventoryListView.as_view(), name='inventory-list'),
    path('trackerdevices/', TrackerDeviceListView.as_view(), name='trackerdevice-list'),
    path('trackerdevices/create/', TrackerDeviceCreateView.as_view(), name='trackerdevice-create'),
    path('trackerdevices/<int:pk>/', TrackerDeviceDetailView.as_view(), name='trackerdevice-detail'),
    path('trackerdevices/<int:pk>/update/', TrackerDeviceUpdateView.as_view(), name='trackerdevice-update'),
    path('trackerdevices/<int:pk>/delete/', TrackerDeviceDeleteView.as_view(), name='trackerdevice-delete'),
    path('sims/', SimListView.as_view(), name='sim-list'),
    path('sims/create/', SimCreateView.as_view(), name='sim-create'),
    path('sims/<int:pk>/', SimDetailView.as_view(), name='sim-detail'),
    path('sims/<int:pk>/update/', SimUpdateView.as_view(), name='sim-update'),
    path('sims/<int:pk>/delete/', SimDeleteView.as_view(), name='sim-delete'),
]

trackermis/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView,PasswordResetView, PasswordResetCompleteView, PasswordResetConfirmView,PasswordResetDoneView
from django.conf.urls.static import static
from django.urls import path, include
from leads.views import landin_page, LandingPageView, SignupView

admin.site.site_header = "Tracker MIS Admin"
admin.site.site_title = "Tracker MIS Admin Portal"
admin.site.index_title = "Welcome to Tracker MIS Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path("leads/", include('leads.urls', namespace="leads")),
    path("agents/", include('agent.urls', namespace="agent")),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(next_page='landing-page'), name='logout'),
    path("reset-password/", PasswordResetView.as_view(), name='reset-password'),
    path("reset-password-done/", PasswordResetDoneView.as_view(), name='password_reset_done'),
    path("password_reset_confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("signup/", SignupView.as_view(), name='signup'),
    path("inventory/", include('inventory.urls', namespace="inventory"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

inventory/models.py
from django.db import models

class TrackerDevice(models.Model):
    model_number = models.CharField(max_length=255)
    vendor = models.CharField(max_length=255)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    imei = models.CharField(max_length=255)

    def __str__(self):
        return self.model_number

class Sim(models.Model):
    MSISDN = models.CharField(max_length=50)
    ICC_ID = models.CharField(max_length=50)
    OPERATOR_CHOICES = [
        ('zong', 'Zong'),
        ('ufone', 'Ufone'),
        ('warid', 'Warid'),
        ('mobilink', 'Mobilink'),
        ('telenor', 'Telenor'),
    ]
    OPERATOR = models.CharField(max_length=50, choices=OPERATOR_CHOICES)
    PACKAGE = models.CharField(max_length=50)

    def __str__(self):
        return self.MSISDN

inventory/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from crispy_bootstrap5.bootstrap5 import FloatingField
from crispy_bootstrap5.bootstrap5 import BS5Accordion
from .models import TrackerDevice, Sim


class TrackerDeviceForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_method = 'post'
    helper.add_input(Submit('submit', 'Save'))
    class Meta:
        model = TrackerDevice
        fields = ['model_number', 'vendor', 'price', 'imei']



class SimFormModel(forms.ModelForm):
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.layout = Layout(
        FloatingField('MSISDN'),
        FloatingField('ICC_ID'),
        FloatingField('OPERATOR'),
        FloatingField('PACKAGE'),
        Submit('submit', 'Save')
    )
    class Meta:
        model = Sim
        fields = ('MSISDN', 'ICC_ID', 'OPERATOR', 'PACKAGE')
        widgets = {
            'OPERATOR': forms.Select(choices=Sim.OPERATOR_CHOICES),
        }
        labels = {
            'MSISDN': 'MSISDN',
            'ICC_ID': 'ICC_ID',
            'PACKAGE': 'PACKAGE',
            'OPERATOR': 'OPERATOR'
        }

inventory/views.py
from django.views.generic import TemplateView, ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import TrackerDevice, Sim


# TrackerDevice views
class InventoryListView(LoginRequiredMixin, TemplateView):
    template_name = "inventory/inventory_list.html"

class TrackerDeviceListView(ListView):
    model = TrackerDevice
    template_name = "inventory/trackerdevice_list.html"

class TrackerDeviceCreateView(LoginRequiredMixin, CreateView):
    model = TrackerDevice
    fields = ['model_number', 'vendor', 'price', 'imei']
    template_name = "inventory/trackerdevice_create.html"
    success_url = reverse_lazy('inventory:trackerdevice-list')

class TrackerDeviceDetailView(LoginRequiredMixin, DetailView):
    model = TrackerDevice
    template_name = "inventory/trackerdevice_detail.html"

class TrackerDeviceUpdateView(LoginRequiredMixin, UpdateView):
    model = TrackerDevice
    fields = ['model_number', 'vendor', 'price', 'imei']
    template_name = "inventory/trackerdevice_update.html"
    success_url = reverse_lazy('inventory:trackerdevice-list')

class TrackerDeviceDeleteView(LoginRequiredMixin, DeleteView):
    model = TrackerDevice
    template_name = "inventory/trackerdevice_delete.html"
    success_url = reverse_lazy('inventory:trackerdevice-list')

# Sim views
class SimListView(LoginRequiredMixin, ListView):
    model = Sim
    template_name = "inventory/sim_list.html"

class SimCreateView(LoginRequiredMixin, CreateView):
    model = Sim
    fields = ['MSISDN', 'ICC_ID', 'OPERATOR', 'PACKAGE']
    template_name = "inventory/sim_create.html"
    success_url = reverse_lazy('inventory:sim-list')

class SimDetailView(LoginRequiredMixin, DetailView):
    model = Sim
    template_name = "inventory/sim_detail.html"

class SimUpdateView(LoginRequiredMixin, UpdateView):
    model = Sim
    fields = ['MSISDN', 'ICC_ID', 'OPERATOR', 'PACKAGE']
    template_name = "inventory/sim_update.html"
    success_url = reverse_lazy('inventory:sim-list')

class SimDeleteView(LoginRequiredMixin, DeleteView):
    model = Sim
    template_name = "inventory/sim_confirm_delete.html"
    success_url = reverse_lazy('inventory:sim-list')

inventory/templates/inventory/inventory_list.html
{% extends "base.html" %}

{% block content %}

<div class="container container-lg">
<ul class="list-group list-group-flush">
  <li class="list-group-item"><a href="{% url 'inventory:trackerdevice-list' %}">Tracker Devices</a></li>
  <li class="list-group-item"><a href="{% url 'inventory:sim-list' %}">Sims</a></li>
</ul>
</div>

{% endblock %}

inventory/templates/inventory/sim_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2>Delete SIM</h2>
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object.MSISDN }}"?</p>
    <input type="submit" value="Confirm">
  </form>
{% endblock %}

inventory/templates/inventory/sim_create.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
  <div class="row" >
<div  class="col">
</div>
<div  class="col">
    <h1>Create Sim record</h1>
    <form method="post">
      {% csrf_token %}
      {% load crispy_forms_tags %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
      </div>
      <div  class="col">
</div>
      </div>
      
  </div>
{% endblock %}

inventory/templates/inventory/sim_detail.html
{% extends "base.html" %}

{% block content %}
  <h2>SIM Details</h2>
  <ul>
    <li>MSISDN: {{ object.MSISDN }}</li>
    <li>ICC-ID: {{ object.ICC_ID }}</li>
    <li>Operator: {{ object.OPERATOR }}</li>
    <li>Package: {{ object.PACKAGE }}</li>
  </ul>
  <a href="{% url 'inventory:sim-update' pk=object.pk %}">Update SIM</a>
  <a href="{% url 'inventory:sim-delete' pk=object.pk %}">Delete SIM</a>
{% endblock %}

inventory/templates/inventory/sim_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Sims</h1>
  <p><a href="{% url 'inventory:sim-create' %}">Create New Sim record</a></p>
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>MSISDN</th>
        <th>ICC_ID</th>
        <th>PACKAGE</th>
        <th>OPERATOR</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for sim in object_list %}
        <tr>
          <td>{{ sim.MSISDN }}</td>
          <td>{{ sim.ICC_ID }}</td>
          <td>{{ sim.PACKAGE }}</td>
          <td>{{ sim.OPERATOR }}</td>
          <td>
            <a href="{% url 'inventory:sim-detail' sim.pk %}">View</a> |
            <a href="{% url 'inventory:sim-update' sim.pk %}">Edit</a> |
            <a href="{% url 'inventory:sim-delete' sim.pk %}">Delete</a>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No sim record found.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

inventory/templates/inventory/sim_update.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
  <div class="row" >
<div  class="col">
</div>
<div  class="col">
    <h1>Create Sim record</h1>
    <form method="post">
      {% csrf_token %}
      {% load crispy_forms_tags %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
      </div>
      <div  class="col">
</div>
      </div>
      
  </div>
{% endblock %}

inventory/templates/inventory/trackerdevice_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2>Delete Tracker Device</h2>
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object.model_number }}"?</p>
    <input type="submit" value="Confirm">
  </form>
{% endblock %}

inventory/templates/inventory/trackerdevice_create.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
  <div class="row" >
<div  class="col">
</div>
<div  class="col">
    <h1>Create Tracker Device</h1>
    <form method="post">
      {% csrf_token %}
      {% load crispy_forms_tags %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
      </div>
      <div  class="col">
</div>
      </div>
      
  </div>
{% endblock %}

inventory/templates/inventory/trackerdevice_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Tracker Device Details</h1>
  <table>
    <tr>
      <th>Model Number</th>
      <td>{{ object.model_number }}</td>
    </tr>
    <tr>
      <th>Vendor</th>
      <td>{{ object.vendor }}</td>
    </tr>
    <tr>
      <th>Price</th>
      <td>{{ object.price }}</td>
    </tr>
    <tr>
      <th>IMEI</th>
      <td>{{ object.imei }}</td>
    </tr>
  </table>
  <p><a href="{% url 'inventory:trackerdevice-update' object.pk %}">Edit Tracker Device</a></p>
{% endblock %}

inventory/templates/inventory/trackerdevice_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Tracker Devices</h1>
  <p><a href="{% url 'inventory:trackerdevice-create' %}">Create New Tracker Device</a></p>
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Model Number</th>
        <th>Vendor</th>
        <th>Price</th>
        <th>IMEI</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for trackerdevice in object_list %}
        <tr>
          <td>{{ trackerdevice.model_number }}</td>
          <td>{{ trackerdevice.vendor }}</td>
          <td>{{ trackerdevice.price }}</td>
          <td>{{ trackerdevice.imei }}</td>
          <td>
            <a href="{% url 'inventory:trackerdevice-detail' trackerdevice.pk %}">View</a> |
            <a href="{% url 'inventory:trackerdevice-update' trackerdevice.pk %}">Edit</a> |
            <a href="{% url 'inventory:trackerdevice-delete' trackerdevice.pk %}">Delete</a>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No tracker devices found.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

inventory/templates/inventory/trackerdevice_update.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
  <div class="row" >
<div  class="col">
</div>
<div  class="col">
    <h1>Update Tracker Device</h1>
    <form method="post">
      {% csrf_token %}
      {% load crispy_forms_tags %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
      </div>
      <div  class="col">
</div>
      </div>
      
  </div>
{% endblock %}