agent/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView
app_name = 'agent'
urlpatterns =[

    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path("<int:pk>/", AgentDetailView.as_view(), name='agent-detail'),
    path("<int:pk>/update/", AgentUpdateView.as_view(), name='agent-update'),
    path("<int:pk>/delete/", AgentDeleteView.as_view(), name='agent-delete')
]

inventory/urls.py
from django.urls import path
from .views import (
    InventoryListView,
    TrackerDeviceListView,
    TrackerDeviceCreateView,
    TrackerDeviceDetailView,
    TrackerDeviceUpdateView,
    TrackerDeviceDeleteView,
    SimListView,
    SimCreateView,
    SimDetailView,
    SimUpdateView,
    SimDeleteView,
)

app_name = 'inventory'

urlpatterns = [
    path('', InventoryListView.as_view(), name='inventory-list'),
    path('trackerdevices/', TrackerDeviceListView.as_view(), name='trackerdevice-list'),
    path('trackerdevices/create/', TrackerDeviceCreateView.as_view(), name='trackerdevice-create'),
    path('trackerdevices/<int:pk>/', TrackerDeviceDetailView.as_view(), name='trackerdevice-detail'),
    path('trackerdevices/<int:pk>/update/', TrackerDeviceUpdateView.as_view(), name='trackerdevice-update'),
    path('trackerdevices/<int:pk>/delete/', TrackerDeviceDeleteView.as_view(), name='trackerdevice-delete'),
    path('sims/', SimListView.as_view(), name='sim-list'),
    path('sims/create/', SimCreateView.as_view(), name='sim-create'),
    path('sims/<int:pk>/', SimDetailView.as_view(), name='sim-detail'),
    path('sims/<int:pk>/update/', SimUpdateView.as_view(), name='sim-update'),
    path('sims/<int:pk>/delete/', SimDeleteView.as_view(), name='sim-delete'),
]

leads/urls.py
from django.urls import path
from .views import (
    lead_list, lead_detail, lead_create, lead_update, lead_delete,
    LeadListView, LeadDetailView, LeadCreatView, LeadDeleteView, LeadUpdateView
)
app_name = "leads"
urlpatterns = [
    path("all/", LeadListView.as_view(), name='lead-list'),
    path("create/", LeadCreatView.as_view(), name='lead-create'),
    path("<int:pk>/", LeadDetailView.as_view(), name='lead-detail'),
    path("<int:pk>/update/", LeadUpdateView.as_view(), name='lead-update'),
    path("<int:pk>/delete/", LeadDeleteView.as_view(), name='lead-delete')
]

trackermis/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView,PasswordResetView, PasswordResetCompleteView, PasswordResetConfirmView,PasswordResetDoneView
from django.conf.urls.static import static
from django.urls import path, include
from leads.views import landin_page, LandingPageView, SignupView

admin.site.site_header = "Tracker MIS Admin"
admin.site.site_title = "Tracker MIS Admin Portal"
admin.site.index_title = "Welcome to Tracker MIS Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path("leads/", include('leads.urls', namespace="leads")),
    path("agents/", include('agent.urls', namespace="agent")),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(next_page='landing-page'), name='logout'),
    path("reset-password/", PasswordResetView.as_view(), name='reset-password'),
    path("reset-password-done/", PasswordResetDoneView.as_view(), name='password_reset_done'),
    path("password_reset_confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("signup/", SignupView.as_view(), name='signup'),
    path("inventory/", include('inventory.urls', namespace="inventory"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<html>
<head>
<link href="{% static 'css/styles.css' %} ">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
{% include "header.html" %}
{% block content %}

{% endblock content %}

</body>

</html>

templates/header.html
<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          
          <li><a href="\" class="nav-link px-2 text-secondary">Home</a></li>
          {% if request.user.is_authenticated  %}
              {% if request.user.is_organisor %}
          <li><a href="{% url 'agent:agent-list' %}" class="nav-link px-2 text-white">Agent</a></li>
               {% endif %}
          <li><a href="{% url 'leads:lead-list' %}" class="nav-link px-2 text-white">Leads</a></li>
          <li><a href="{% url 'inventory:inventory-list' %}" class="nav-link px-2 text-white">Inventory</a></li>
         
           {% endif %}
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>
        {% if request.user.is_authenticated %}
        <div class="text-end">
        Logged in as : {{ request.user.username }}
        <a href="{% url 'logout' %}" class="btn btn-outline-light me-2">Logout</a>
        </div>
        {% else %}
        <div class="text-end">
          <a href="{% url 'login' %}" class="btn btn-outline-light me-2">Login</a>
          <a href="{% url 'signup' %}" class="btn btn-warning">Sign-up</a>
        {% endif %}
      </div>
    </div>
  </header>

templates/landing_page.html
{% extends "base.html" %}
{% block content %}
<div class="bg-dark text-secondary px-4 py-5 text-center">
    <div class="py-5">
      <h1 class="display-5 fw-bold text-white">Tracker MIS</h1>
      <div class="col-lg-6 mx-auto">
        <p class="fs-5 mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
          <a href="login/" type="button" class="btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold">Login</a>
          <a href="signup/" type="button" class="btn btn-outline-light btn-lg px-4">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}