agent/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView
app_name = 'agent'
urlpatterns =[

    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path("<int:pk>/", AgentDetailView.as_view(), name='agent-detail'),
    path("<int:pk>/update/", AgentUpdateView.as_view(), name='agent-update'),
    path("<int:pk>/delete/", AgentDeleteView.as_view(), name='agent-delete')
]

trackermis/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView,PasswordResetView, PasswordResetCompleteView, PasswordResetConfirmView,PasswordResetDoneView
from django.conf.urls.static import static
from django.urls import path, include
from leads.views import landin_page, LandingPageView, SignupView

admin.site.site_header = "Tracker MIS Admin"
admin.site.site_title = "Tracker MIS Admin Portal"
admin.site.index_title = "Welcome to Tracker MIS Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path("leads/", include('leads.urls', namespace="leads")),
    path("agents/", include('agent.urls', namespace="agent")),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(next_page='landing-page'), name='logout'),
    path("reset-password/", PasswordResetView.as_view(), name='reset-password'),
    path("reset-password-done/", PasswordResetDoneView.as_view(), name='password_reset_done'),
    path("password_reset_confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("signup/", SignupView.as_view(), name='signup'),
    path("inventory/", include('inventory.urls', namespace="inventory"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agent/models.py
from django.db import models

agent/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()
class AgentFormModel(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name'
        )

agent/views.py
import random
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views.generic import (TemplateView, ListView, DeleteView, DetailView,
                CreateView,UpdateView
                                  )
from leads.models import Agent
from .mixins import OrganisorandLoginRequiredMixin
from .forms import AgentFormModel

class AgentListView(OrganisorandLoginRequiredMixin, ListView):
    template_name = "agent/gent_list.html"
    
    def get_queryset(self):
        organisation =self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)
    
class AgentCreateView(OrganisorandLoginRequiredMixin, CreateView):
    template_name = 'agent/agent_create.html'
    form_class = AgentFormModel

    def get_success_url(self):
        return reverse('agent:agent-list')
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.password= "aghabro123"
        #user.set_password(f"{random.randint(0, 1000000)}")
        user.save()
        Agent.objects.create(
            user = user,
            organisation = self.request.user.userprofile
        )
        #agent.organisation = self.request.user.userprofile
        #agent.save()
        return super(AgentCreateView, self).form_valid(form)

class AgentDetailView(OrganisorandLoginRequiredMixin, DetailView):
    template_name = "agent/agent_detail.html"
    context_object_name = 'agent'
    def get_queryset(self):
        organisation =self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)
    
class AgentUpdateView(OrganisorandLoginRequiredMixin, UpdateView):
    template_name = 'agent/agent_update.html'
    queryset = Agent.objects.all()
    form_class = AgentFormModel
    def get_success_url(self):
        return reverse('agent:agent-list')
class AgentDeleteView(OrganisorandLoginRequiredMixin, DeleteView):
    template_name = "agent/agent_delete.html"
    queryset = Agent.objects.all()
    def get_success_url(self):
        return reverse('agent:agent-list')
    def get_queryset(self):
        organisation =self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

agent/templates/agent/agent_create.html
{% extends 'base.html' %}

{% block content %}
  <div class="container container-md">
  <div class="row" >
<div  class="col">
</div>
<div  class="col">
    <h1>Create Agent</h1>
    <form method="post">
      {% csrf_token %}
      {% load crispy_forms_tags %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
      </div>
      <div  class="col">
</div>
      </div>
      
  </div>
{% endblock %}

agent/templates/agent/agent_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="container container-md">
  <div class="row" >
<div  class="col">
</div>
<div  class="col">
    <h1>Are you sure to delete agent : {{agent.user.username}}</h1>
    <form method="post">
      {% csrf_token %}
      {% load crispy_forms_tags %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Delete</button>
    </form>
      </div>
      <div  class="col">
</div>
      </div>
      
  </div>
{% endblock %}

agent/templates/agent/agent_detail.html
{% extends "base.html" %}
{% block content %}
<div>
<a href="{% url 'agent:agent-list' %}">Go back</a>
<p>Agent name is : {{agent.user.username}}</p>

<hr />
<a href="{% url 'agent:agent-update' agent.pk %}">Update</a>
<a href="{% url 'agent:agent-delete' agent.pk %}">Delete</a>
</div>
{% endblock content %}

agent/templates/agent/agent_update.html
{% extends 'base.html' %}

{% block content %}
  <div class="container container-md">
  <div class="row" >
<div  class="col">
</div>
<div  class="col">
    <h1>Edit Agent</h1>
    <form method="post">
      {% csrf_token %}
      {% load crispy_forms_tags %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
      </div>
      <div  class="col">
</div>
      </div>
      
  </div>
{% endblock %}

agent/templates/agent/gent_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container-md">
  <h1>Agents</h1>
  <p><a href="{% url 'agent:agent-create' %}">Create New Agent</a></p>
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>User Name</th>
   
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for agent in object_list %}
        <tr>
          <td>{{agent.user.username}}</td>
      
          <td>
            <a href="{% url 'agent:agent-detail' agent.pk %}">View</a> |
            <a href="{% url 'agent:agent-update' agent.pk %}">Edit</a> |
            <a href="{% url 'agent:agent-delete' agent.pk %}">Delete</a>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No Agent found.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
{% endblock %}